conda-forge/openff-evaluator-feedstock

.ci_support/linux_64_.yaml, recipe/meta.yaml
=> Release 0.3.6

.azure-pipelines/azure-pipelines-linux.yml, .gitattributes, .scripts/build_steps.sh, .scripts/run_docker_build.sh, README.md, build-locally.py, recipe/build_base.sh, recipe/meta.yaml
=> Split package into base and main

recipe/meta.yaml
=> Release 0.3.9

recipe/meta.yaml
=> Update to 0.3.11

.ci_support/linux_64_.yaml, .circleci/config.yml, .github/CODEOWNERS, .scripts/build_steps.sh, LICENSE.txt, README.md, build-locally.py, recipe/conda_build_config.yaml, recipe/meta.yaml
Copying my own homework https://github.com/conda-forge/openff-interchange-feedstock/pull/17
cc: @j-wags 
Checklist
=> Build v0.4.0rc1

recipe/meta.yaml
=> Build v0.4.0rc2

.ci_support/linux_64_.yaml, recipe/conda_build_config.yaml
=> Fix syntax in recipe/conda_build_config.yaml

recipe/meta.yaml
=> Fix SHA hash

recipe/meta.yaml
=> Add @j-wags as a maintainer

.ci_support/linux_64_.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml
=> 0.3.11 build 1 (downpin OFF toolkit)

.ci_support/linux_64_.yaml, .github/CODEOWNERS, README.md, recipe/meta.yaml
=> Release v0.4.0rc4

.ci_support/linux_64_.yaml, recipe/conda_build_config.yaml, recipe/meta.yaml
=> Release v0.4.0

.circleci/config.yml, .scripts/build_steps.sh, recipe/meta.yaml
=> Loosen MDtraj constraint

.gitignore, recipe/meta.yaml
=> Downpin against OpenMM 8

.gitignore, .scripts/build_steps.sh, README.md, recipe/meta.yaml
=> Avoid pulling down old `jaxlib`

recipe/meta.yaml
=> Release 0.4.3

recipe/meta.yaml
=> Constrain pandas

recipe/meta.yaml
=> Release 0.4.5

.scripts/build_steps.sh, .scripts/logging_utils.sh, recipe/meta.yaml
@j-wags found that the "whole" package was not updated when the base package was
Checklist
=> Update MDTraj constraints

.scripts/build_steps.sh, recipe/meta.yaml
=> Release 0.4.6

recipe/meta.yaml
=> Release 0.4.7

.azure-pipelines/azure-pipelines-linux.yml, .gitignore, .scripts/build_steps.sh, .scripts/run_docker_build.sh, README.md, recipe/meta.yaml
=> Release 0.4.8
